folio-org/stripes-data-transfer-components

CHANGELOG.md
index.js
lib/utils/getFileExtension.js
lib/utils/index.js
lib/utils/tests/getFileExtension-test.js

Added getFileExtension function from ui-data-import to utils here because of reuse in scope of the [UIDEXP-21](https://issues.folio.org/browse/UIDEXP-21)

UIDEXP-21: move getFileExtension from ui-data-import

---

CHANGELOG.md
package.json

Updating `stripes-smart-components` to `v3.0.0` will help to avoid errors (for example current errors in tests)

UIDEXP-37: Update stripes-smart-components to correct test run

---

CHANGELOG.md
index.js
lib/Settings/ProfilesLabel/ProfilesLabel.css
lib/Settings/ProfilesLabel/ProfilesLabel.js
lib/Settings/ProfilesLabel/index.js
lib/Settings/ProfilesLabel/tests/ProfilesLabel-test.js
lib/Settings/ProfilesLabel/tests/interactors/ProfilesLabelInteractor.js
lib/Settings/ProfilesLabel/tests/interactors/ProfilesPopoverInteractor.js
lib/Settings/ProfilesLabel/tests/interactors/index.js
lib/Settings/SettingsLabel/SettingsLabel.js
lib/Settings/SettingsLabel/index.js
lib/Settings/SettingsLabel/tests/SettingsLabel-test.js
lib/Settings/SettingsLabel/tests/interactor.js
lib/Settings/index.js
translations/stripes-data-transfer-components/en.json

Add shared components SettingsLabel and ProfilesLabel in scope of adding the second settings pane. [Story](https://issues.folio.org/browse/UIDEXP-39).

UIDEXP-39: Add shared components for second settings pane

---

interactors.js
lib/SearchForm/tests/SearchForm-test.js
lib/SearchForm/tests/interactor.js

Export interactors so other modules would not need to specify in the import the path to the whole project structure (e.g. `import SearchFormInteractor from '@folio/stripes-data-transfer-components/lib/SearchForm/tests/interactor';`) to the needed interactor and thus depend on the structure.

UIDEXP-51: Export interactors

---

CHANGELOG.md
lib/JobLogs/defaultJobLogsProps.js

UIDEXP-58: Remove `totalRecords` value from `defaultJobLogsColumnWidths` settings for the jobs logs list in the scope of the [UIDEXP-58](https://issues.folio.org/browse/UIDEXP-58).

UIDEXP-58: Remove totalRecords value from defaultJobLogsColumnWidths

---

CHANGELOG.md
lib/utils/sort.js
lib/utils/tests/sort-test.js

Adjust `sortNumbers` function to work correctly with null values in the scope of the [UIDEXP-58](https://issues.folio.org/browse/UIDEXP-58).

UIDEXP-58: Adjust sortNumbers function to work correctly with empty values

---

CHANGELOG.md
lib/FileUploader/FileUploader.js

Handle "form elements must have labels" accessibility problem for file uploader form in the scope of [STDTC-7](https://issues.folio.org/secure/RapidBoard.jspa?rapidView=112).

STDTC-7: Handle "form elements must have labels" accessibility problem for file uploader form

---

CHANGELOG.md
lib/Jobs/Job/Job.css
lib/Jobs/Job/Job.js
lib/Jobs/JobsList/JobsList.css
lib/Jobs/JobsList/JobsList.js

Update jobs list structure according to the accessibility requirements in the scope of [UIDEXP-49](https://issues.folio.org/browse/UIDEXP-49).
Make sure that immediate children of `<ul>` tags be `<li>` elements.

UIDEXP-49: Update jobs list structure according to the accessibility requirements

---

CHANGELOG.md
lib/Jobs/JobsList/JobsList.js
lib/SearchForm/tests/SearchForm-test.js
lib/SearchResults/SearchResults.js
lib/SearchResults/index.js
lib/SearchResults/tests/SearchResults-test.js
lib/SearchResults/tests/interactor.js
lib/Settings/MappingProfiles/MappingProfiles.js
lib/Settings/MappingProfiles/tests/MappingProfiles-test.js
lib/Settings/MappingProfiles/tests/interactor.js

Create a reusable `SearchResults` view component in the scope of [STDTC-8](https://issues.folio.org/browse/STDTC-8).

STDTC-8: Create reusable search results view component

---

lib/FullScreenForm/tests/interactor.js

Improve `FullScreenForm` iteractor by providing namespace for pane header in order to be able to use it in other repositories.

UIDEXP-96: Improve FullScreenForm iteractor

---

CHANGELOG.md
index.js
lib/utils/folioRecordTypes.js
translations/stripes-data-transfer-components/en.json

Extend FOLIO record types list and export shared test utils to prevent code duplication. [Story](https://issues.folio.org/browse/UIDEXP-46)

UIDEXP-46: Export test utils and extend FOLIO record types list

---

CHANGELOG.md
interactors.js

Export PreloaderInteractor for tests in ui-data-export. [Story](https://issues.folio.org/browse/UIDEXP-82)

UIDEXP-82: Export PreloaderInteractor

---

lib/ListTemplate/listTemplate.js
lib/ListTemplate/tests/listTemplate-test.js
lib/Settings/MappingProfiles/listTemplate.js
lib/Settings/MappingProfiles/tests/listTemplate-test.js

Clean up warnings in the console below:
* WARN: 'Formatter possibly needed for column 'folioRecord': value is object;
* WARN: 'Formatter possibly needed for column 'updatedBy';

UIDEXP-47: Clean up warnings in the console

---

CHANGELOG.md
lib/JobLogs/listTemplate.js
lib/JobLogs/tests/listTemplate-test.js
lib/tests/jobExecution.js
lib/tests/jobsLogs.js

When none of records were exported successfully, value in `Records` should be empty according to the requirements.
[UIDEXP-97](https://issues.folio.org/browse/UIDEXP-97)

UIDEXP-97: Update record column for failed status

---

CHANGELOG.md
interactors.js
lib/Jobs/jobExecutionPropTypes.js

Export ProgressInteractor and update job execution proptypes according to changes on backend side. [Story](https://issues.folio.org/browse/UIDEXP-38)

UIDEXP-38: Export ProgressInteractor and update job execution prop types

---

CHANGELOG.md
lib/Jobs/jobExecutionPropTypes.js
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js
lib/Settings/JobProfiles/JobProfiles.js
lib/Settings/JobProfiles/tests/JobProfiles-test.js

Extend `SearchAndSortPane`  and `JobProfiles` with new props in order to adjust it for choose job profile page in the scope of [UIDEXP-87](https://issues.folio.org/browse/UIDEXP-87).
List of new props:
`SearchAndSortPane`:
- `hasSearchForm` - for making it possible to hide search form (`true` by default);
- `lastMenu` - for making it possible to provide custom header last menu (nothing by default);
- `searchResultsProps` - for making it possible to provide custom search results props which would make it possible to override some existing props and provide new ones (`{}` by default);
`JobProfiles`:
- `titleId` - for making it possible to provide custom title id (`stripes-data-transfer-components.jobProfilesTitle` by default);

UIDEXP-87: Extend `SearchAndSortPane` and `JobProfiles` with new props in order to adjust it for choose job profile page

---

CHANGELOG.md
lib/JobLogs/listTemplate.js
lib/JobLogs/tests/listTemplate-test.js

The user info can't be provided in some cases according to the latests information. So the check is added to prevent the main page crashing. [Issue](https://issues.folio.org/browse/UIDEXP-107).

UIDEXP-107: Fix error screen display in case of missed user information in job executions

---

CHANGELOG.md
interactors.js
lib/Settings/ProfilesLabel/tests/interactors/ProfilesPopoverInteractor.js

Update properties (link to content and scope) in ProfilesPovoerInteractor and export ProfilesPovoerInteractor. [Story](https://issues.folio.org/browse/UIDEXP-53)

UIDEXP-53: Update properties in ProfilesPopoverInteractor and export ProfilesLabelInteractors

---

CHANGELOG.md
package.json

Move `react-intl` from `^4.5` to `~4.6` to avoid the broken `4.7` series, https://github.com/formatjs/formatjs/issues/1744.

Move react-intl from ^4.5 to ~4.6 to avoid broken changes in 4.7

---

CHANGELOG.md
lib/JobLogs/listTemplate.js
lib/JobLogs/tests/jobLogs-test.js
lib/JobLogs/tests/listTemplate-test.js
lib/Jobs/jobExecutionPropTypes.js
lib/tests/jobExecution.js
lib/tests/jobsLogs.js
package.json

Add job names display from backend response instead of "default" value. [Story](https://issues.folio.org/browse/UIDEXP-116)
**Additional change:** unpin react-intl version according to broken change fixing in 4.7.2
**Screenshots:**

UIDEXP-116: Add job name display in job logs and executions

---

CHANGELOG.md
lib/Settings/SettingsLabel/SettingsLabel.js
lib/Settings/SettingsLabel/tests/SettingsLabel-test.js
package.json

Extend `SettingsLabel` with ability to provide arbitrary label content in the scope of the [UIDEXP-86](https://issues.folio.org/browse/UIDEXP-86).

UIDEXP-86: Extend `SettingsLabel` with ability to provide arbitrary label content

---

package.json

Provide a correct `actsAs` key to the stripes config in the scope of the [UIDEXP-86](https://issues.folio.org/browse/UIDEXP-86).

UIDEXP-86: Provide a correct `actsAs` key to the stripes config

---

package.json

I have a hunch that because of usage of `actsAs` instead of `type` in stripes config for some reason environments now retrieve the stale version of the package which now breaks stuff. Let's see if returning to the previous approach will help.

Try to fix stale version envs

---

.eslintrc
CHANGELOG.md
lib/FullScreenForm/tests/FullScreenForm-test.js
lib/FullScreenView/FullScreenView.js
lib/FullScreenView/tests/FullScreenView-test.js
lib/SearchAndSortPane/SearchAndSortPane.js
package.json
translations/stripes-data-transfer-components/en.json

* Extend `FullScreenView` to accept `actionMenu` prop
* Sync up eslint config with data-export
* Replace deprecated `type` with `actAs` in package.json
in the scope of the [UIDEXP-84](https://issues.folio.org/browse/UIDEXP-84).

UIDEXP-84: Extend `FullScreenView` to accept `actionMenu` prop

---

CHANGELOG.md
lib/FullScreenForm/tests/FullScreenForm-test.js
lib/FullScreenView/FullScreenView.js
lib/FullScreenView/tests/FullScreenView-test.js

Extend FullScreenView Component to support renderHeader prop. (Component will be used in data-import module. refers to ticket https://issues.folio.org/browse/UIDATIMP-535)
- Add support of renderHeader prop to make component more flexible for usage in different cases
- Remove setting focus on cancel button to have the same behaviour as in other places

UIDATIMP-535: Update FullScreenView Component to support renderHeader prop.

---

CHANGELOG.md
CODESTYLEGUIDE.md
README.md
lib/FullScreenForm/FullScreenForm.js

Update `FullScreenView` component to support `noValidate` prop in the scope of the [STDTC-16](https://issues.folio.org/browse/STDTC-16).

STDTC-16: Update `FullScreenView` component to support `noValidate` prop

---

CHANGELOG.md
lib/DataFetcher/DataFetcher.js
lib/FileUploader/FileUploader.js
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js

Extend `SortAndSearchPane` to accept `excludedSortColumns` and `shouldSetInitialSortOnMount` prop in the scope of the [UIDEXP-142](https://issues.folio.org/browse/UIDEXP-142).

UIDEXP-142: Extend `SortAndSearchPane` to accept `excludedSortColumns` and `shouldSetInitialSortOnMount` prop

---

CHANGELOG.md
lib/Settings/ProfilesLabel/tests/ProfilesLabel-test.js
lib/Settings/ProfilesLabel/tests/interactors/ProfilesLabelInteractor.js
lib/Settings/ProfilesLabel/tests/interactors/ProfilesPopoverInteractor.js

https://issues.folio.org/browse/UIDEXP-190
The markup for the `<InfoPopover>` in stripes-components was changed slightly recently, making the tests break in this repo because of invalid scopes in some interactors. This PR fixes that.

UIDEXP-190: Update scopes related to InfoPopover in interactors to fix tests

---

translations/stripes-data-transfer-components/en.json

In the scope of [[UIDEXP-178]](https://issues.folio.org/browse/UIDEXP-178)
Rolling back translation to it's previous state, since this translation is used in other places, where it supposed to stay the same.

UIDEXP-178: Rollback the Instance reacord type translation

---

CHANGELOG.md
lib/SearchForm/SearchForm.js
lib/SearchForm/tests/SearchForm-test.js

1. Add `idKey` prop to the component to avoid accessibility problems with duplicated `ids` when there is more than one `<SearchForm>` on the page.
2. Add `fieldName` prop to the component to be able to set the `name` to the search field.
[UIDATIMP-582](https://issues.folio.org/browse/UIDATIMP-582)

UIDATIMP-582: Extend `<SearchForm>` component with additional props

---

CHANGELOG.md
lib/JobLogs/useJobLogsListFormatter.js

In the sope of [STDTC-21](https://issues.folio.org/browse/STDTC-21).
For some edge cases, the progress field for job log is not provided, which causes UI to break. This PR prevents UI from breaking.

STDTC-21: Handle missing job progress field

---

CHANGELOG.md
package.json

Update module version and changelog after bugfix v3.0.2 release in the scope of the [STDTC-22](https://issues.folio.org/browse/STDTC-22).

STDTC-22: Update module version and changelog after bugfix v3.0.2 release

---

CHANGELOG.md
test/jest/helpers/getHookExecutionResult.js

In scope of [UIDEXP-143](https://issues.folio.org/browse/UIDEXP-143).
Update `getHookExecutionResult` in order for it to be able to return function.

UIDEXP-143: Update getHookExecutionResult in order for it to be able to return function

---

CHANGELOG.md
package.json

Move pretender to dev dependencies in the scope of the [UIDEXP-186](https://issues.folio.org/browse/UIDEXP-186).

UIDEXP-186: Move pretender to dev dependencies

---

CHANGELOG.md
lib/FileUploader/FileUploader.js

should also fix UIDEXP-210 - Change focus when user clicks on Data export app
- autoFocus property has been added to upload button
[UIDATIMP-775](https://issues.folio.org/browse/UIDATIMP-775)
[UIDEXP-210](https://issues.folio.org/browse/UIDEXP-210)

UIDATIMP-775 - Change focus when user clicks on Data import app

---

CHANGELOG.md
interactors.js
test/bigtest/helpers/getHookExecutionResult.js

Export `getHookExecutionResult` for BigTest tests in the scope of the [UIDEXP-213](https://issues.folio.org/browse/UIDEXP-213).

UIDEXP-213: Export `getHookExecutionResult` for Bigtest tests

---

CHANGELOG.md
test/jest/helpers/getHookExecutionResult.js

Adjust it for BigTest and jest and to work with translations in the scope of the [UIDEXP-213](https://issues.folio.org/browse/UIDEXP-213).

UIDEXP-213: Adjust `getHookExecutionResult` for jest tests

---

CHANGELOG.md
lib/Progress/Progress.js
lib/Progress/tests/Progress-test.js

https://issues.folio.org/browse/UIF-237
basically, it enables to use not defined progressInfoType to hide progress description.

UIF-237 enable Progress with 'none' type

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchResults/SearchResults.js

Refactor `onNeedMore` function for `SearchResults` component to be able to fetch data by `offset` param.
- Add a condition to `onNeedMore`  function to check whether `resultOffset` prop is provided.
[UIDATIMP-763](https://issues.folio.org/browse/UIDATIMP-763)

UIDATIMP-763: Refactor `onNeedMore` function for `SearchResults` component

---

CHANGELOG.md
package.json

In the scope of [STDTC-35](https://issues.folio.org/browse/STDTC-35).
Bump the stripes dependency to version 6.0.0 so UI can work with the latest changes from the modules there. Task also covers the update of stripes related dependencies which also should be updated after the stripes update.

STDTC-35: Update `stripes` to `v6.0.0`

---

CHANGELOG.md
package.json
test/bigtest/helpers/mountWithContext.js
test/helpers/Harness.js
test/jest/helpers/renderWithIntl.js

Extend `Harnses` test setup component with react-query and stripes providers in the scope of the [UIDEXP-224](https://issues.folio.org/browse/UIDEXP-224).

UIDEXP-224: Extend `Harnses` test setup component with react-query and stripes providers

---

CHANGELOG.md
package.json

Update `stripes-cli` to `v2.0.0` in the scope of the [STDTC-38](https://issues.folio.org/browse/STDTC-38)

STDTC-38: Update `stripes-cli` to `v2.0.0`

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js

Add `firstMenu` prop to the component to be able to render `x` icon so a user can navigate back.
https://issues.folio.org/browse/UIDATIMP-913

UIDATIMP-913: Add `firstMenu` prop to the `SearchAndSortPane` component

---

CHANGELOG.md
lib/utils/sort.js

In Kiwi Bugfest, on the Data Import landing page, clicking on the file name column header to re-sort the column results in an error message.
Records, created through API, has no fileName property, so when we trying to sort by fileName column, it's cause to displayed of error message. 
Default value for parameters of sortStrings function were added

STDTC-52 - Log sort on Data Import landing page not working properly.

---

CHANGELOG.md
package.json

* To use unreleased features, we increased SDTC version from `v5.3.0` to `v5.4.0`
[STDTC-74](https://issues.folio.org/browse/STDTC-74)

STDTC-74: Bump SDTC version to v5.4.0

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchResults/SearchResults.js

Endless "job-profiles" requests when select job profile to run data export
[STDTC-86](https://issues.folio.org/browse/STDTC-86)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

STDTC-86: Endless "job-profiles" requests when select job profile to run data export

---

CHANGELOG.md
lib/FileUploader/FileUploader.js

For accessibility reasons, it was necessary to remove aria-hidden=true, since for users with a screen reader this element was hidden but not hidden for focus, which could be misleading.
[STDTC-98](https://issues.folio.org/browse/STDTC-98)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

STDTC-98 Hidden element has focusable content

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilters.js
package.json

https://folio-org.atlassian.net/browse/STDTC-105
We apply tenant date-time in `Started running`, `Ended running` filters, as it done in` ui-inventory`

STDTC-105: Apply tenant date-time when filter data export logs by date on View all page

---

CHANGELOG.md
lib/utils/formatUserName.js
lib/utils/tests/formatUserName.test.js

* Since the requirements have changed, we need to replace displaying **Updated by** column with the new format **Last name, first name (@user_name)**
[STDTC-109](https://folio-org.atlassian.net/browse/STDTC-109)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

STDTC-109: Display `Updated by` column in the format `Last name, first name (@user_name)`

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js

Replace annotations such as `@withStripes` with a [`_.flow()`](https://lodash.com/docs/4.17.15#flow)-based syntax for better compatibility with esbuild-loader >= 3.1.0.
Refs [STDTC-122](https://folio-org.atlassian.net/browse/STDTC-122)

STDTC-122 apply wrappers with flow()
