folio-org/stripes-data-transfer-components

package.json
test/bigtest/.eslintrc
test/bigtest/connectStripes.js
test/bigtest/helpers/Harness.js
test/bigtest/helpers/getCleanTestingRoot.js
test/bigtest/helpers/hasClassBeginningWith.js
test/bigtest/helpers/index.js
test/bigtest/helpers/mount.js
test/bigtest/helpers/mountWithContext.js
test/bigtest/helpers/prefixKeys.js
test/bigtest/helpers/selectorFromClassnameString.js
test/bigtest/index.js
test/bigtest/network/boot.js
test/bigtest/network/config.js
test/bigtest/network/index.js

Setup tests as part of [UIDEXP-11](https://issues.folio.org/browse/UIDEXP-11).

UIDEXP-11: Setup tests

---

CHANGELOG.md
index.js
lib/EndOfItem/tests/interactor.js
lib/FileUploader/FileUploader.css
lib/FileUploader/FileUploader.js
lib/FileUploader/defaultStyles.css
lib/FileUploader/index.js
lib/FileUploader/readme.md
lib/FileUploader/tests/FileUploader-test.js
lib/FileUploader/tests/interactor.js
package.json

Add `FileUploader` component in the scope of [UIDEXP-11](https://issues.folio.org/browse/UIDEXP-11).

UIDEXP-11: Add FileUploader component

---

translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/pt_BR.json

Update translation strings as of 20200207T143033

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ur.json

Update translation strings as of 20200210T220102

---

CHANGELOG.md
index.js
lib/FileUploader/FileUploader.css
lib/FileUploader/tests/FileUploader-test.js
lib/FileUploader/utils/index.js
lib/FileUploader/utils/tests/uploadFile-test.js
lib/FileUploader/utils/uploadFile.js
lib/Preloader/Preloader.js
lib/Preloader/tests/Preloader-test.js
lib/utils/convertBytesToKilobytes.js
lib/utils/createOkapiHeaders.js
lib/utils/createUrl.js
lib/utils/index.js
lib/utils/tests/convertBytesToKilobytes-test.js
lib/utils/tests/createOkapiHeaders-test.js
lib/utils/tests/createUrl-test.js
package.json

Add shared utils for initiating the data export process as a part of the [UIDEXP-20](https://issues.folio.org/browse/UIDEXP-20).

UIDEXP-20: Add shared utils for initiating data export process

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200302T163727

---

.eslintrc
CHANGELOG.md
Jenkinsfile
index.js
lib/DataFetcher/DataFetcher.js
lib/DataFetcher/index.js
lib/DataFetcher/tests/DataFetcher-test.js
lib/utils/constants.js

Implement `DataFetcher` component for making API requests upon interval in the scope of the [UIDEXP-22](https://issues.folio.org/browse/UIDEXP-22).

UIDEXP-22: Implement DataFetcher component for making API requests upon interval

---

lib/DataFetcher/DataFetcher.js

React to resources update in the `DataFetcher` in the scope of [UIDEXP-22](https://issues.folio.org/browse/UIDEXP-22).

UIDEXP-22: React to resources update in the DataFetcher

---

CHANGELOG.md

Release module for the FOLIO 2020Q1. Refs [UIDEXP-27](https://issues.folio.org/browse/UIDEXP-27).

UIDEXP-27: Release 1.0.0

---

CHANGELOG.md
index.js
lib/DataFetcher/tests/DataFetcher-test.js
lib/SearchForm/SearchForm.css
lib/SearchForm/SearchForm.js
lib/SearchForm/index.js
lib/SearchForm/tests/SearchForm-test.js
lib/SearchForm/tests/interactor.js
test/bigtest/helpers/Harness.js
test/bigtest/helpers/mountWithContext.js
test/bigtest/helpers/prefixKeys.js

Add `SearchForm` component in the scope of [UIDEXP-51](https://issues.folio.org/browse/UIDEXP-51).

UIDEXP-51: Implement SearchForm component

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200331T152557

---

CHANGELOG.md
package.json

Update module version changelog after bugfix v1.0.1 release in the scope of the [STDTC-1](https://issues.folio.org/browse/STDTC-1).

STDTC-1: Update module version changelog after bugfix v1.0.1 release

---

translations/stripes-data-transfer-components/pt_BR.json

Update translation strings as of 20200403T124750

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200406T162815

---

translations/stripes-data-transfer-components/ja.json

Update translation strings as of 20200420T134821

---

translations/stripes-data-transfer-components/ja.json

Update translation strings as of 20200421T180634

---

translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200424T193712

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200505T210535

---

CHANGELOG.md
lib/Settings/SettingsLabel/tests/interactor.js
package.json

Update to Stripes v4 in the scope of [STDTC-10](https://issues.folio.org/browse/STDTC-10).

STDTC-10: Update to Stripes v4

---

translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200513T135229

---

.eslintrc
CHANGELOG.md
lib/DataFetcher/tests/DataFetcher-test.js
lib/JobLogs/withJobLogsSort.js
lib/ListTemplate/index.js
lib/ListTemplate/listTemplate.js
lib/ListTemplate/tests/listTemplate-test.js
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js
lib/SearchResults/tests/SearchResults-test.js
lib/Settings/JobProfiles/JobProfiles.js
lib/Settings/JobProfiles/columnProperties.js
lib/Settings/JobProfiles/getItemFormatter.js
lib/Settings/JobProfiles/index.js
lib/Settings/JobProfiles/tests/JobProfiles-test.js
lib/Settings/JobProfiles/tests/jobProfilesData.js
lib/Settings/MappingProfiles/listTemplate.js
lib/Settings/MappingProfiles/tests/MappingProfiles-test.js
lib/Settings/index.js
lib/utils/combineMCLProps.js
lib/utils/tests/combineMCLProps-test.js
package.json
translations/stripes-data-transfer-components/en.json

Implement job profiles list in the scope of [UIDEXP-80](https://issues.folio.org/browse/UIDEXP-80).

UIDEXP-80: Implement JobProfiles list component

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200515T182823

---

translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200519T123842

---

CHANGELOG.md
lib/ListTemplate/listTemplate.js
lib/ListTemplate/tests/listTemplate-test.js
lib/Settings/MappingProfiles/listTemplate.js
lib/Settings/MappingProfiles/tests/MappingProfiles-test.js
lib/Settings/MappingProfiles/tests/listTemplate-test.js
lib/Settings/MappingProfiles/tests/mappingProfilesData.js

- Update formatter for column `updatedBy` in case it doesn't get any value
- Update formatter for column `folioRecord` in case it get an array of records
[UIDEXP-57](https://issues.folio.org/browse/UIDEXP-57)
relates to [PR](https://github.com/folio-org/ui-data-export/pull/70)

UIDEXP-57: update mapping profile formatter

---

translations/stripes-data-transfer-components/fr_FR.json

Update translation strings as of 20200526T141248

---

translations/stripes-data-transfer-components/ru.json

Update translation strings as of 20200602T151309

---

CHANGELOG.md
interactors.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js
lib/Settings/JobProfiles/tests/JobProfiles-test.js
lib/Settings/MappingProfiles/tests/MappingProfiles-test.js
test/bigtest/helpers/stripesResourcesMocks.js

Export test utilities for building resources and mutators in the scope of [UIDEXP-87](https://issues.folio.org/browse/UIDEXP-87).

UIDEXP-87: Export test utilities for building resources and mutators

---

CHANGELOG.md
index.js
interactors.js
lib/FullScreenForm/FullScreenForm.js
lib/FullScreenView/FullScreenView.css
lib/FullScreenView/FullScreenView.js
lib/FullScreenView/index.js
lib/FullScreenView/tests/FullScreenView-test.js
lib/FullScreenView/tests/interactor.js

Add `FullScreenView` component for render record details on full pane
part of [UIDEXP-50](https://issues.folio.org/browse/UIDEXP-50)

UIDEXP-50: Add FullScreenView component

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js

Changes according to this [comment](https://github.com/folio-org/ui-data-export/pull/87#issuecomment-643251173)

UIDEXP-50: Change `SearchAndSortPane` rowProp `href` with `to`

---

CHANGELOG.md
package.json

Release module for the FOLIO 2020Q2. Refs [STDTC-11](https://issues.folio.org/browse/STDTC-11).

STDTC-11: Release v2.0.0

---

translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/zh_CN.json

Update translation strings as of 20200615T161518

---

translations/stripes-data-transfer-components/ru.json

Update translation strings as of 20200623T182030

---

translations/stripes-data-transfer-components/ru.json

Update translation strings as of 20200624T130324

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20200707T213422

---

CHANGELOG.md
package.json

Update module version and changelog after bugfix v2.0.1 release in the scope of the [STDTC-12](https://issues.folio.org/browse/STDTC-12).

STDTC-12: Update module version and changelog after bugfix v2.0.1 release

---

translations/stripes-data-transfer-components/fr_FR.json

Update translation strings as of 20200716T140311

---

translations/stripes-data-transfer-components/zh_CN.json

Update translation strings as of 20200721T202356

---

translations/stripes-data-transfer-components/it_IT.json

Update translation strings as of 20200824T140725

---

CHANGELOG.md
index.js
interactors.js
lib/JobLogs/JobLogs.js
lib/OverlayView/OverlayView.js
lib/OverlayView/index.js
lib/OverlayView/tests/OverlayView-test.js
lib/OverlayView/tests/interactor.js

Add OverlayView component and extend JobLogs API to add transition to the error logs. [Story](https://issues.folio.org/browse/UIDEXP-18)

UIDEXP-18: Add OverlayView component and extend JobLogs API

---

CHANGELOG.md
lib/SearchForm/SearchForm.js
lib/Settings/JobProfiles/JobProfiles.js
lib/Settings/MappingProfiles/MappingProfiles.js
lib/utils/formatTranslationChunks.js
lib/utils/index.js
lib/utils/tests/formatTranslationChunks-test.js
package.json

[STDTC-15](https://issues.folio.org/browse/STDTC-15)
Update react-intl to v5.7.0 and fix warnings about failed prop types.

STDTC-15: Update react-intl to v5.7.0

---

CHANGELOG.md
lib/JobLogs/useJobLogsListFormatter.js
lib/ListFormatter/useListFormatter.js
lib/utils/index.js
lib/utils/iso8601Timestamp.js
lib/utils/useDateFormatter.js
lib/utils/useTimeFormatter.js

Fix date and time display in Safari extending react-intl solution. [Story](https://issues.folio.org/browse/UIDEXP-175)
**Note**: This is a temp solution that was partly copied from stripes-components because stripes-components had already released and can't be changed for our purposes. useDateFormatter and useTimeFormatted should be moved to the shared place during the next release.

UIDEXP-175: Fix date and time display in Safary

---

CHANGELOG.md
package.json

[STDTC-17](https://issues.folio.org/browse/STDTC-17)
`stripes-data-transfer-components` v3.0.0 release

STDTC-17: Release v3.0.0

---

translations/stripes-data-transfer-components/ar.json
translations/stripes-data-transfer-components/ca.json
translations/stripes-data-transfer-components/da.json
translations/stripes-data-transfer-components/de.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json
translations/stripes-data-transfer-components/en_US.json
translations/stripes-data-transfer-components/es.json
translations/stripes-data-transfer-components/es_419.json
translations/stripes-data-transfer-components/es_ES.json
translations/stripes-data-transfer-components/fr.json
translations/stripes-data-transfer-components/fr_FR.json
translations/stripes-data-transfer-components/he.json
translations/stripes-data-transfer-components/hi_IN.json
translations/stripes-data-transfer-components/hu.json
translations/stripes-data-transfer-components/it_IT.json
translations/stripes-data-transfer-components/ja.json
translations/stripes-data-transfer-components/ko.json
translations/stripes-data-transfer-components/pl.json
translations/stripes-data-transfer-components/pt_BR.json
translations/stripes-data-transfer-components/pt_PT.json
translations/stripes-data-transfer-components/ru.json
translations/stripes-data-transfer-components/ur.json
translations/stripes-data-transfer-components/zh_CN.json
translations/stripes-data-transfer-components/zh_TW.json

Update translation strings as of 20201105T151643

---

translations/stripes-data-transfer-components/it_IT.json

Update translation strings as of 20201111T142927

---

translations/stripes-data-transfer-components/ja.json

Update translation strings as of 20201124T212804

---

.eslintrc
CHANGELOG.md
lib/DataFetcher/DataFetcher.js
lib/DataFetcher/tests/DataFetcher-test.js
lib/FullScreenForm/tests/interactor.js
lib/utils/sortCollection.js

Rewrite `DataFetcher` using the functional component notation in the scope of the [STDTC-34](https://issues.folio.org/browse/STDTC-34).

STDTC-34: Rewrite `DataFetcher` using functional component notation

---

CHANGELOG.md
package.json

In the scope of  [STDTC-37](https://issues.folio.org/browse/STDTC-37).
`stripes-data-transfer-components` v4.0.0 release.

STDTC-37: Release v4.0.0

---

CHANGELOG.md

STDTC-37: Update CHANGELOG.md

---

CHANGELOG.md
package.json

Release v4.1.0 in the scope of the [STDTC-39](https://issues.folio.org/browse/STDTC-39).

STDTC-39: Release v4.1.0

---

lib/ListFormatter/useListFormatter.test.js
lib/OverlayView/OverlayView.js
lib/OverlayView/OverlayView.test.js
test/jest/__new_mock__/index.js
test/jest/__new_mock__/reactIntl.mock.js

https://issues.folio.org/browse/STDTC-28 …

STDTC-28 Rewrite Bigtest tests for ListFormatter, OverlayView with jest/react-testing-library

---

lib/EndOfItem/tests/EndOfItem.test.js
lib/FullScreenForm/FullScreenForm.js
lib/FullScreenForm/FullScreenForm.test.js
lib/FullScreenView/FullScreenView.js
lib/FullScreenView/FullScreenView.test.js
pull_request_template.md
test/jest/__mock__/index.js
test/jest/__mock__/reactIntl.mock.js

https://issues.folio.org/browse/STDTC-25 …

STDTC-25 Rewrite Bigtest tests for FullScreenForm, FullScreenView with jest/react-testing-library

---

CHANGELOG.md
lib/FileUploader/FileUploader.css
lib/FileUploader/FileUploader.js
lib/FileUploader/tests/FileUploader-test.js
lib/FileUploader/tests/interactor.js
package.json

https://issues.folio.org/browse/STDTC-40 …

STDTC-40 Upgrade to latest react-dropzone

---

lib/Jobs/Job/Job.js
lib/Jobs/Job/Job.test.js
lib/Jobs/JobsList/JobsList.js
lib/Jobs/JobsList/JobsList.test.js
lib/Jobs/JobsListAccordion/JobsListAccordion.test.js
lib/Jobs/RunningJobs/sortRunningJobs.test.js

https://issues.folio.org/browse/STDTC-27 …

STDTC-27: Rewrite Bigtest tests for Jobs with jest/react-testing-library

---

lib/Jobs/JobsListAccordion/JobsListAccordion.test.js
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js
lib/Settings/JobProfiles/tests/JobProfiles-test.js
lib/Settings/MappingProfiles/tests/MappingProfiles-test.js

https://issues.folio.org/browse/STDTC-46 …

STDTC-46 Add the ability to filter by name for SearchAndSortPane component

---

lib/FileUploader/FileUploader.js
lib/FileUploader/FileUploader.test.js
lib/Jobs/JobsListAccordion/JobsListAccordion.test.js
lib/SearchAndSortPane/tests/SearchAndSortPane-test.js
lib/Settings/ProfilesLabel/tests/ProfilesLabel-test.js

https://issues.folio.org/browse/STDTC-43 …

STDTC-43: add jest/react-testing-library tests for FileUploader

---

lib/Settings/JobProfiles/JobProfiles.test.js
lib/Settings/MappingProfiles/MappingProfiles.test.js
lib/Settings/MappingProfiles/useMappingProfileListFormatter.test.js
lib/Settings/ProfilesLabel/ProfilesLabel.test.js
lib/Settings/SettingsLabel/SettingLabel.test.js

https://issues.folio.org/browse/STDTC-33 …

STDTC-33: add jest/react-testing-library tests for Settings components

---

lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchAndSortPane/SearchAndSortPane.test.js
lib/SearchForm/SearchForm.js
lib/Settings/ProfilesLabel/tests/ProfilesLabel-test.js

https://issues.folio.org/browse/STDTC-30 …

STDTC-30 Rewrite Bigtest tests for SearchAndSortPane with jest/react-testing-library

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js

https://issues.folio.org/browse/STDTC-48 …

STDTC-48 Fix "Load more" button in SearchAndSortPane

---

lib/FileUploader/FileUploader.js
test/jest/babel.config.js

https://issues.folio.org/browse/STDTC-51 …

Add disable prop in FileUploader

---

lib/FileUploader/FileUploader.js

https://issues.folio.org/browse/UIBULKED-24
While it's helpful for reviewers to help …

Disable upload button

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilterConfig.js
lib/ViewAllLogsFilters/ViewAllLogsFilters.js
lib/ViewAllLogsFilters/ViewAllLogsFilters.test.js
lib/ViewAllLogsFilters/constants.js
lib/ViewAllLogsFilters/index.js
package.json
test/jest/__mock__/index.js
test/jest/__mock__/matchMedia.mock.js
translations/stripes-data-transfer-components/en.json

https://issues.folio.org/browse/STDTC-19 …

STDTC-19: Move ViewAllLogsFilters component from data-import

---

CHANGELOG.md
package.json

Compile translations for increased runtime efficiency.
Refs [STDTC-59](https://issues.folio.org/browse/STDTC-59)
Attn: @uladislausamets I don't have write access to this repo; if this looks good, please merge it!

STDTC-59 compile translations

---

CHANGELOG.md
package.json

[STDTC-66](https://issues.folio.org/browse/STDTC-66) …

Release v5.2.1

---

CHANGELOG.md
package.json

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

Release 5.3.0

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilters.js
lib/ViewAllLogsFilters/constants.js

[STDTC-68](https://issues.folio.org/browse/STDTC-68) …

STDTC-68: Change status values in ViewAllLogsFilters

---

lib/ViewAllLogsFilters/constants.js
translations/stripes-data-transfer-components/en.json
translations/stripes-data-transfer-components/en_GB.json
translations/stripes-data-transfer-components/en_SE.json

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

STDTC-68: Update translation

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilters.js

[STDTC-70](https://issues.folio.org/browse/STDTC-70) …

STDTC-70: Fix logic in range filter in ViewAllLogsFilters

---

CHANGELOG.md
test/helpers/Harness.js

Created based on @zburke [PR](https://github.com/folio-org/stripes-data-transfer-components/pull/226)

STDTC-71 suppress react-intl warnings in test harness

---

CHANGELOG.md
lib/utils/createOkapiHeaders.js
lib/utils/tests/createOkapiHeaders.test.js

https://issues.folio.org/browse/STDTC-73 …

STDTC-73 leverage cookie-based authentication in all API requests

---

lib/FileUploader/utils/uploadFile.js

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

STDTC-73 add missed withCredentials option in request

---

CHANGELOG.md
lib/FileUploader/FileUploader.js

[STDTC-75](https://issues.folio.org/browse/STDTC-75) …

STDTC-75: Fix Accessibility in FileUploader component

---

CHANGELOG.md
package.json

[STDTC-76](https://issues.folio.org/browse/STDTC-76) …

STDTC-76: Move pretender to dev-deps

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/STDTC-79 …

STDTC-79 bump stripes to 8.0.0 for Orchid/2023-R1

---

CHANGELOG.md
lib/utils/tests/useFormattedMLCProps.test.js
test/helpers/Harness.js
test/jest/helpers/renderWithContext.js

Avoid private paths in stripes-core imports.
https://issues.folio.org/browse/STDTC-81

STDTC-81: Avoid private paths in stripes-core imports

---

CHANGELOG.md
lib/SearchAndSortPane/SearchAndSortPane.js
lib/SearchResults/SearchResults.js
lib/SearchResults/SearchResults.test.js

[STDTC-85](https://issues.folio.org/browse/STDTC-85) …

STDTC-85: Add additional props to SearchAndSortPane

---

CHANGELOG.md
lib/JobLogs/columnProperties.js
lib/JobLogs/withJobLogsSort.js
lib/ListTemplate/listTemplate.js
lib/ListTemplate/listTemplate.test.js
lib/utils/sort.js
test/jest/__mock__/reactIntl.mock.js

* Use `formatNumber` function instead of `<FormattedNumber />`.
* Add `jobProfileName` prop to the log if it doesn't exist to allow sorting by job profile name.
[STDTC-88](https://issues.folio.org/browse/STDTC-88)
[UIDATIMP-1454](https://issues.folio.org/browse/UIDATIMP-1454)
https://github.com/folio-org/stripes-data-transfer-components/assets/85172747/a71ea714-00ba-4cde-a9c7-86a6ce262ce7
https://github.com/folio-org/stripes-data-transfer-components/assets/85172747/a087869b-ae27-4962-9d30-3c019a8ed4f4
- What other modules …

STDTC-88: Allow to sort logs by `totalRecords` and `job profile` columns

---

CHANGELOG.md
translations/stripes-data-transfer-components/en.json

STDTC-90: Replace all caps in Filter option
[STDTC-90](https://issues.folio.org/browse/STDTC-90)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

STDTC-90: Replace all caps in Filter option

---

.eslintrc
.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
lib/DataFetcher/DataFetcher.js
lib/FileUploader/FileUploader.test.js
package.json

[STDTC-93](https://issues.folio.org/browse/STDTC-93) …

STDTC-93: Update Node.js to v18 in GitHub Actions

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilters.js
lib/ViewAllLogsFilters/ViewAllLogsFilters.test.js
lib/ViewAllLogsFilters/constants.js
package.json
test/jest/__mock__/stripesCore.mock.js

https://issues.folio.org/browse/STDTC-94 …

STDTC-94 Add User filter to Logs page

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilters.js
lib/utils/index.js
lib/utils/onFilter.js
lib/utils/tests/onFilter.test.js

[STDTC-99](https://issues.folio.org/browse/STDTC-99)
Here we add onFilter function to make search more consistent. Onfilter function give us possibility to search letter on any position of that letter, without it - it search only on first position 
On the attached video we can see how it works with onFilter and without on snapshot env
https://github.com/folio-org/stripes-data-transfer-components/assets/72550466/48d741ea-6511-4f1b-8e6b-5253836f180e

STDTC-99: Add onfilter function to ViewAllLogsFilter

---

CHANGELOG.md
lib/ListTemplate/listTemplate.js
lib/ListTemplate/listTemplate.test.js

https://issues.folio.org/browse/STDTC-100 …

STDTC-100 Formatting a list of jobs without the progress field results in an error on the UI

---

CHANGELOG.md
lib/utils/constants.js

Fix a crash when viewing Authority DELETE job profile details.
[STDTC-102](https://issues.folio.org/browse/STDTC-102)
Job profile for deletion ("Authority DELETE job") is only added to the env https://folio-dev-spitfire-diku.ci.folio.org/
Screencast will be added once the rancher env is restored.
Ideally all of the PRs involved in breaking changes would be …

STDTC-102: Fix a crash when viewing Authority DELETE job profile details.

---

lib/utils/calculatePercentage.js

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

UIDEXP-357 calculatePercentage - return 0 if NaN

---

CHANGELOG.md
lib/ViewAllLogsFilters/ViewAllLogsFilters.js
translations/stripes-data-transfer-components/en.json

https://folio-org.atlassian.net/browse/STDTC-97
We added `onFilter` logic and updated name of filter regarding changes in https://folio-org.atlassian.net/browse/UIDEXP-370

STDTC-97: Add User look-up filter for existing jobs to Logs page

---

lib/ViewAllLogsFilters/ViewAllLogsFilters.js

https://folio-org.atlassian.net/browse/STDTC-105
Small fix to existing story

STDTC-105: Apply tenant date-time when filter data export logs by date on View all page

---

CHANGELOG.md
lib/DataFetcher/DataFetcher.js
lib/FileUploader/FileUploader.js
lib/JobLogs/JobLogs.js
lib/ListTemplate/ColumnTemplates/DefaultColumn.js
lib/Preloader/Preloader.js
lib/SearchForm/SearchForm.js
lib/Settings/JobProfiles/JobProfiles.js
lib/Settings/MappingProfiles/MappingProfiles.js
lib/Settings/SettingsLabel/SettingsLabel.js
lib/ViewAllLogsFilters/ViewAllLogsFilters.js

https://folio-org.atlassian.net/browse/STDTC-113
Here we refatored away from default props for functional components

STDTC-113: React v19: refactor away from default props for functional components

---

CHANGELOG.md
lib/JobLogs/JobLogs.js
lib/SearchResults/SearchResults.test.js

https://folio-org.atlassian.net/browse/STDTC-116
Here we added new prop `showSortIndicator` to `JobLogs` component

STDTC-116: Add showSortIndicator prop to JobLogs component
